[workspace]
members = [
   "lib_reversi",
   "game_runner",
   "lib_boardgame",
   "monte_carlo_tree",
   "lib_agents",
   "lib_tic_tac_toe",
   "reversi_nboard_runner",
   "lib_printer",
   "lib_connect_four"
]