[package]
name = "lib_agents"
version = "0.1.0"
authors = ["andy salerno <andysalerno@gmail.com>"]
edition = "2018"

[dependencies]
util = { path = "../util" }
lib_boardgame = {path = "../lib_boardgame" }