[package]
name = "util"
version = "0.1.0"
authors = ["andy salerno <andysalerno@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.6"
lib_boardgame = { path = "../lib_boardgame" }
lib_reversi = { path = "../lib_reversi" }