[package]
name = "monte_carlo_tree"
version = "0.1.0"
authors = ["andy <andysalerno@gmail.com>"]
edition = "2018"

[dependencies]
lib_boardgame = {path = "../lib_boardgame" }
lib_tic_tac_toe = {path = "../lib_tic_tac_toe" }
crossbeam = "0.7.2"